FROM node:22-slim

# Directorio de trabajo local dentro del Alpine
WORKDIR /app

# Copiamos temporalmente los package files
COPY package.json package-lock.json* ./

# Instalamos internamente todas las dependencias
RUN npm install

# Copiar el grueso de la app al working dir
COPY . .

EXPOSE 3000

# Iniciamos Next.js 
CMD ["npm", "run", "dev"]
