/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/blaster.glb -o src/components/player/BlasterModel.tsx -t 
Author: o0ozexo0o (https://sketchfab.com/dadndan0091)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arx-160-weapon-d0fdd93f90bb47eea8c98bbb2ae85d40
Title: ARX-160 weapon
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
  };
  materials: {
    material_0: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function BlasterModel(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "/models/blaster.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/blaster.glb");
